import http from "k6/http";
import exec from "k6/execution";
import { check, fail, sleep } from "k6";
import { Rate, Trend } from "k6/metrics";

export const baseUrl = (__ENV.K6_BASE_URL || "http://127.0.0.1:4000").replace(/\/$/, "");
export const defaultPassword = __ENV.K6_SIGNIN_PASSWORD || "DemoPass123!";
export const defaultThinkTimeMin = Number(__ENV.K6_THINK_TIME_MIN || 0.2);
export const defaultThinkTimeMax = Number(__ENV.K6_THINK_TIME_MAX || 1.0);

const defaultSeededUsers = [
  {
    email: "emily.rodriguez@umass.edu",
    expectedUserId: "a1000000-0000-0000-0000-000000000001"
  },
  {
    email: "michael.chen@umass.edu",
    expectedUserId: "a1000000-0000-0000-0000-000000000002"
  },
  {
    email: "sarah.johnson@umass.edu",
    expectedUserId: "a1000000-0000-0000-0000-000000000003"
  },
  {
    email: "chen.lab@umass.edu",
    expectedUserId: "a1000000-0000-0000-0000-000000000004"
  }
];
const configuredSigninEmails = splitEnvList(__ENV.K6_SIGNIN_EMAILS);
const configuredExpectedUserIds = splitEnvList(__ENV.K6_SIGNIN_EXPECTED_USER_IDS);

export const seededUsers =
  configuredSigninEmails.length > 0
    ? configuredSigninEmails.map((email, index) => ({
        email,
        expectedUserId: configuredExpectedUserIds[index] || null
      }))
    : defaultSeededUsers;

export const listingsLatency = new Trend("fcc_listings_latency", true);
export const listingDetailsLatency = new Trend("fcc_listing_details_latency", true);
export const searchLatency = new Trend("fcc_search_latency", true);
export const authLatency = new Trend("fcc_auth_latency", true);
export const notificationsLatency = new Trend("fcc_notifications_latency", true);
export const applicationsLatency = new Trend("fcc_applications_latency", true);
export const createListingLatency = new Trend("fcc_create_listing_latency", true);
export const deleteListingLatency = new Trend("fcc_delete_listing_latency", true);
export const apiChecks = new Rate("fcc_api_checks");

export function buildThresholds(p95Ms = 800, failedRate = 0.02) {
  return {
    http_req_failed: [`rate<${failedRate}`],
    http_req_duration: [`p(95)<${p95Ms}`, `p(99)<${Math.max(p95Ms * 2, p95Ms + 500)}`],
    checks: ["rate>0.99"],
    fcc_api_checks: ["rate>0.99"]
  };
}

export function jsonParams(token) {
  const headers = {
    "Content-Type": "application/json"
  };

  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }

  return { headers };
}

export function think(minSeconds = defaultThinkTimeMin, maxSeconds = defaultThinkTimeMax) {
  const max = Math.max(maxSeconds, minSeconds);
  const delay = minSeconds + Math.random() * (max - minSeconds);
  sleep(delay);
}

export function parseJson(response) {
  try {
    return response.json();
  } catch {
    return null;
  }
}

export function recordTrend(trend, response) {
  trend.add(response.timings.duration);
}

export function requestJson(name, method, path, body = null, params = undefined) {
  const response = http.request(
    method,
    `${baseUrl}${path}`,
    body ? JSON.stringify(body) : null,
    params
  );
  const ok = check(response, {
    [`${name} returned JSON`]: (res) => {
      const contentType = String(res.headers["Content-Type"] || "");
      return contentType.includes("application/json");
    }
  });

  apiChecks.add(ok);
  return response;
}

export function signInAccount(account) {
  const response = requestJson("signin", "POST", "/api/auth/signin", {
    email: account.email,
    password: defaultPassword
  }, jsonParams());

  recordTrend(authLatency, response);

  const payload = parseJson(response);
  const ok = check(response, {
    "signin status is 200": (res) => res.status === 200,
    "signin returns auth token": () => Boolean(payload?.authToken),
    "signin returns expected user": () => matchesExpectedUser(payload, account)
  });

  apiChecks.add(ok);

  if (!ok) {
    fail(`Unable to sign in seeded account ${account.email}`);
  }

  return {
    ...account,
    token: payload.authToken,
    userId: payload.user.id
  };
}

export function signInSeededUsers() {
  return seededUsers.map(signInAccount);
}

export function pickAccount(accounts) {
  return accounts[(exec.vu.idInTest - 1) % accounts.length];
}

export function pickRandom(items) {
  return items[Math.floor(Math.random() * items.length)];
}

export function matchesExpectedUser(payload, account) {
  if (!account.expectedUserId) {
    return Boolean(payload?.user?.id);
  }

  return payload?.user?.id === account.expectedUserId;
}

export function createListingPayload(vuId, iterationInScenario) {
  const stamp = `${Date.now()}-${vuId}-${iterationInScenario}`;

  return {
    title: `k6 load listing ${stamp}`,
    description: "Generated by k6 to measure listing create/delete throughput.",
    category: "project",
    contactMethod: "email",
    contactDetails: "load-test@umass.edu",
    bannerImageUrl: "",
    customColor: "#123456",
    status: "open",
    expirationDate: "2026-12-31",
    skills: [],
    attachments: []
  };
}

function splitEnvList(value) {
  return String(value || "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}
